#version
cms.title=ctcms
cms.version=CT CMS 1.6.75

#cms.user=ryanius
cms.user=skc

# 서버 기동시 자동 모두배포
cms.autoPublish=false
#cms.autoPublish=true

cms.storage=none
#cms.storage=zadara
#cms.storage=google

#tronix storage
#cms.storage=tronix
#cms.storage.url=http://<HOST>:7001
#cms.storage.secretKey=<SECRET>


# DBMS 종류
db.type = mysql

#db.type = oracle

# mysql 드라이버
mysql.driver=com.mysql.jdbc.Driver
# 오라클 드라이버
oracle.driver=oracle.jdbc.driver.OracleDriver

# MYSQL - 본사실섭 - tronix
#mysql.url=jdbc:mysql://<HOST>:3306/tronix2019
#mysql.username=<USER>
#mysql.password=<PASSWORD>

# MYSQL - 본사테섭 - txcms
mysql.db=test

#로컬서버
#mysql.url=jdbc:mysql://localhost:3306/test
#mysql.username=root
#mysql.password=<PASSWORD>

#본섭버
#mysql.url=jdbc:mysql://<HOST>:3306/monitoring
mysql.url=jdbc:mysql://<HOST>:3306/monitering
mysql.username=<USER>
mysql.password=<PASSWORD>

# oracleLVDCgetData_To
#oracle.url=jdbc:oracle:thin:@<HOST>:1521:xe
#oracle.username=<USER>
#oracle.password=<PASSWORD>

# MYSQL - InitData
#mysql.url=jdbc:mysql://<HOST>:3306/ctcms
#mysql.username=<USER>
#mysql.password=<PASSWORD>

#오라클 하려면 일단 이거 사용하세요
oracle.url=jdbc:oracle:thin:@<HOST>:1521:xe
oracle.username=<USER>
oracle.password=<PASSWORD>


#slowlog
slowlog.time=0.2
slowlog.path=D:/slowlog/

#hook